project_id = "sowlwwoesurgvgjykiow"

[functions.update-user-role]
verify_jwt = false

[functions.upload-avatar]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.course-actions]
verify_jwt = false
